#!/usr/bin/env bash
#
# build-adapters.sh — adapter generator (M2-T5).
#
# What it does
#   Reads the five canonical agent definitions in agents/*.md (YAML
#   frontmatter + markdown body) and the Claude frontmatter overlays in
#   skills/etyb/adapters/claude/overlays/*.yaml, and emits every
#   harness-specific adapter surface:
#
#     .codex/agents/etyb_{explorer,planner,reviewer,stack_researcher,cartographer}.toml
#         Codex custom-agent TOML. Fields follow the pre-existing hand-written
#         TOMLs: name, description, model, model_reasoning_effort,
#         sandbox_mode, developer_instructions. Codex model ids are pinned in
#         CODEX_META below (carried over from the previous hand-written files;
#         etyb_stack_researcher inherits etyb_docs_researcher's, which it
#         supersedes and whose file this script removes). sandbox_mode is
#         derived from the agent's tools: Write/Edit present -> workspace-write,
#         otherwise read-only. developer_instructions = the agent .md body,
#         passed through verbatim.
#
#     dist/adapters/kiro/agents/etyb-{explorer,planner,reviewer,stack-researcher,cartographer}.json
#         Kiro CLI custom-agent config (minimal-valid: name, description,
#         prompt, tools). Claude tools map to Kiro built-ins:
#         Read/Glob/Grep -> fs_read, Bash -> execute_bash, Write -> fs_write;
#         WebFetch has no Kiro built-in equivalent and is noted in "_notes".
#         JSON cannot carry comments, so the header lives in "_generated".
#
#     dist/adapters/cursor/.cursor-plugin/
#         Cursor plugin skeleton: plugin.json (name "etyb", version from the
#         repo VERSION file), agents/*.md with name/description/model
#         frontmatter (Cursor subagent format), and skills/README.md
#         explaining that Cursor reads the same shared skills/ tree — skill
#         content is deliberately NOT duplicated here.
#
#     dist/adapters/claude-plugin-skills/etyb-{review,plan,explore}/SKILL.md
#         The merged Claude plugin copies of the thin role skills: the
#         overlay's top-level frontmatter keys are deep-merged into the shared
#         SKILL.md frontmatter (overlay wins on conflict), body passes through
#         unchanged. These prove the M2-T2 overlay mechanism; the shared tree
#         stays portable (lint-portability.sh keeps guaranteeing it). A future
#         release step copies these merged files into the Claude plugin
#         packaging — until then dist/ is the reference emission.
#
#   Every emitted file carries a
#   "# GENERATED by scripts/build-adapters.sh — edit agents/ + overlays instead"
#   header (as a "_generated" field where the format is JSON).
#
# Determinism / CI drift idiom
#   Output is byte-stable: agents are processed in a fixed order, YAML/JSON
#   are rendered with fixed key order and formatting, and no run-varying data
#   is written. Running the script twice produces byte-identical output, so
#   CI checks drift with:
#
#     bash scripts/build-adapters.sh && git diff --exit-code \
#       .codex/agents dist/adapters
#
# Dependencies: bash, python3 with PyYAML (stdlib tomllib is only needed by
# the verification step, not by generation).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

command -v python3 >/dev/null 2>&1 || { echo "✗ python3 is required" >&2; exit 1; }
python3 -c 'import yaml' 2>/dev/null || { echo "✗ python3 PyYAML is required" >&2; exit 1; }

# etyb_docs_researcher was the hand-written predecessor of the generated
# etyb_stack_researcher; remove it so the directory holds exactly the five
# generated agents. rm -f keeps this idempotent.
rm -f .codex/agents/etyb_docs_researcher.toml

python3 - "$ROOT" <<'PY'
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(sys.argv[1])

HEADER = "GENERATED by scripts/build-adapters.sh — edit agents/ + overlays instead"
DRIFT = "CI drift check: bash scripts/build-adapters.sh && git diff --exit-code .codex/agents dist/adapters"

# Fixed processing order — part of the determinism contract.
AGENTS = [
    "etyb-explorer",
    "etyb-planner",
    "etyb-reviewer",
    "etyb-stack-researcher",
    "etyb-cartographer",
]

# Codex model pins, carried over from the previous hand-written TOMLs (this
# generator never invents Codex model ids). etyb_stack_researcher inherits
# from etyb_docs_researcher (superseded); etyb_cartographer follows
# etyb_reviewer's conventions.
CODEX_META = {
    "etyb-explorer": ("gpt-5.4-mini", "medium"),
    "etyb-planner": ("gpt-5.4", "high"),
    "etyb-reviewer": ("gpt-5.4", "high"),
    "etyb-stack-researcher": ("gpt-5.4-mini", "medium"),
    "etyb-cartographer": ("gpt-5.4", "high"),
}

# Claude tool -> Kiro CLI built-in tool. WebFetch maps to None: Kiro has no
# built-in web-fetch tool (it arrives via MCP), so it is dropped from "tools"
# and disclosed in "_notes".
KIRO_TOOL_MAP = {
    "Read": "fs_read",
    "Glob": "fs_read",
    "Grep": "fs_read",
    "Bash": "execute_bash",
    "Write": "fs_write",
    "Edit": "fs_write",
    "WebFetch": None,
}

ROLE_SKILLS = ["etyb-explore", "etyb-plan", "etyb-review"]


def parse_agent_md(path: pathlib.Path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise SystemExit(f"✗ {path}: missing YAML frontmatter")
    fm_text, _, body = text[4:].partition("\n---\n")
    fm = yaml.safe_load(fm_text)
    return fm, body.lstrip("\n").rstrip("\n")


def split_frontmatter(path: pathlib.Path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise SystemExit(f"✗ {path}: missing YAML frontmatter")
    fm_text, sep, body = text[4:].partition("\n---\n")
    if not sep:
        raise SystemExit(f"✗ {path}: unterminated YAML frontmatter")
    return yaml.safe_load(fm_text), body


def deep_merge(base, overlay):
    """Overlay wins; dicts merge recursively; everything else replaces."""
    merged = dict(base)
    for key, value in overlay.items():
        if key in merged and isinstance(merged[key], dict) and isinstance(value, dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '""\\"')
    return '"""\n' + escaped + '\n"""'


def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  emitted {path.relative_to(ROOT)}")


def tools_list(fm) -> list:
    raw = fm.get("tools", "")
    if isinstance(raw, str):
        return [t.strip() for t in raw.split(",") if t.strip()]
    return list(raw)


agents = {}
for name in AGENTS:
    fm, body = parse_agent_md(ROOT / "agents" / f"{name}.md")
    agents[name] = {"fm": fm, "body": body, "tools": tools_list(fm)}

# ---------------------------------------------------------------- Codex TOML
for name in AGENTS:
    a = agents[name]
    model, effort = CODEX_META[name]
    writes = any(t in ("Write", "Edit") for t in a["tools"])
    sandbox = "workspace-write" if writes else "read-only"
    toml = (
        f"# {HEADER}\n"
        f"# {DRIFT}\n"
        f"name = {toml_str(name.replace('-', '_'))}\n"
        f"description = {toml_str(a['fm']['description'])}\n"
        f"model = {toml_str(model)}\n"
        f"model_reasoning_effort = {toml_str(effort)}\n"
        f"sandbox_mode = {toml_str(sandbox)}\n"
        f"developer_instructions = {toml_multiline(a['body'])}\n"
    )
    write(ROOT / ".codex" / "agents" / f"{name.replace('-', '_')}.toml", toml)

# ----------------------------------------------------------------- Kiro JSON
for name in AGENTS:
    a = agents[name]
    kiro_tools, unmapped = [], []
    for t in a["tools"]:
        mapped = KIRO_TOOL_MAP.get(t)
        if mapped is None:
            unmapped.append(t)
        elif mapped not in kiro_tools:
            kiro_tools.append(mapped)
    doc = {
        "_generated": f"{HEADER}. {DRIFT}",
        "name": name,
        "description": a["fm"]["description"],
        "prompt": a["body"],
        "tools": kiro_tools,
    }
    if unmapped:
        doc["_notes"] = (
            "No Kiro built-in equivalent for: " + ", ".join(unmapped)
            + ". Provide via MCP if needed."
        )
    write(
        ROOT / "dist" / "adapters" / "kiro" / "agents" / f"{name}.json",
        json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
    )

# ------------------------------------------------------------ Cursor plugin
version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
cursor_root = ROOT / "dist" / "adapters" / "cursor" / ".cursor-plugin"
plugin = {
    "_generated": f"{HEADER}. {DRIFT}",
    "name": "etyb",
    "version": version,
    "description": (
        "ETYB engineering co-pilot — orchestrator skill plus specialist "
        "subagents (explorer, planner, reviewer, stack-researcher, "
        "cartographer)."
    ),
    "author": {"name": "e-t-y-b"},
    "license": "MIT",
    "homepage": "https://github.com/e-t-y-b/etyb-skills",
}
write(
    cursor_root / "plugin.json",
    json.dumps(plugin, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
)

for name in AGENTS:
    a = agents[name]
    fm = {
        "name": name,
        "description": a["fm"]["description"],
        "model": a["fm"].get("model", "inherit"),
    }
    fm_yaml = yaml.safe_dump(
        fm, sort_keys=False, allow_unicode=True, default_flow_style=False, width=78
    )
    md = f"---\n# {HEADER}\n# {DRIFT}\n{fm_yaml}---\n\n{a['body']}\n"
    write(cursor_root / "agents" / f"{name}.md", md)

skills_readme = f"""<!-- {HEADER} -->
<!-- {DRIFT} -->

# Skills — shared tree, not duplicated

Cursor reads the same portable skills tree every other harness reads:
`skills/` at the repo root (`skills/etyb/` — the orchestrator — plus the
thin `skills/etyb-explore/`, `skills/etyb-plan/`, and `skills/etyb-review/`
role skills). Point Cursor's skills discovery at that directory (e.g. via
`.cursor/skills/`, per `docs/installation.md`).

Skill content is deliberately NOT copied into this plugin skeleton:
duplicating it would fork the source of truth and defeat the shared-tree
guarantee that `scripts/lint-portability.sh` enforces.
"""
write(cursor_root / "skills" / "README.md", skills_readme)

# ---------------------------------------- Claude plugin skills (overlay merge)
for skill in ROLE_SKILLS:
    src = ROOT / "skills" / skill / "SKILL.md"
    overlay_path = ROOT / "skills" / "etyb" / "adapters" / "claude" / "overlays" / f"{skill}.yaml"
    fm, body = split_frontmatter(src)
    overlay = yaml.safe_load(overlay_path.read_text(encoding="utf-8"))
    merged = deep_merge(fm, overlay)
    fm_yaml = yaml.safe_dump(
        merged, sort_keys=False, allow_unicode=True, default_flow_style=False, width=78
    )
    out = f"---\n# {HEADER}\n# {DRIFT}\n{fm_yaml}---{body}"
    write(ROOT / "dist" / "adapters" / "claude-plugin-skills" / skill / "SKILL.md", out)

print("build-adapters: done")
PY
